version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: development
    container_name: ems-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/models/face:/app/models/face
      - /app/node_modules

    command: npm run dev
    networks:
      - ems-network
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      target: development
    container_name: ems-worker-dev
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev:workers
    networks:
      - ems-network
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: ems-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - ems-network

  redis:
    image: redis:7-alpine
    container_name: ems-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - ems-network

networks:
  ems-network:
    driver: bridge

volumes:
  redis_data_dev:
