import React from 'react';
import { Link } from 'react-router-dom';
import { useReportHistory } from '../../hooks/useReports.js';
import { DataTable } from '../../components/ui/DataTable.jsx';
import { Button } from '../../components/ui/Button.jsx';

export function ReportHistoryPage() {
  const { data, isLoading } = useReportHistory();
  const histories = data?.data?.histories || [];

  const columns = [
    {
      header: 'Report File',
      key: 'fileName',
      render: (r) => (
        <div>
          <div className="font-semibold text-slate-100">{r.fileName}</div>
          <div className="text-xs text-slate-400 font-mono">{r.type}</div>
        </div>
      )
    },
    {
      header: 'Format',
      key: 'format',
      render: (r) => (
        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-mono bg-slate-800 text-slate-300 border border-slate-700">
          {r.format || 'CSV'}
        </span>
      )
    },
    {
      header: 'Generated By',
      key: 'user',
      render: (r) => (
        <span className="text-xs text-slate-300">
          {r.user ? `${r.user.firstName} ${r.user.lastName}` : 'System / Admin'}
        </span>
      )
    },
    {
      header: 'Status',
      key: 'status',
      render: (r) => {
        const colors = {
          COMPLETED: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
          PENDING: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
          FAILED: 'bg-red-500/10 text-red-400 border-red-500/30'
        };
        const status = r.status || 'COMPLETED';
        return (
          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold border ${colors[status] || colors.COMPLETED}`}>
            {status}
          </span>
        );
      }
    },
    {
      header: 'Date',
      key: 'createdAt',
      render: (r) => (
        <span className="text-xs text-slate-400 font-mono">
          {r.createdAt ? new Date(r.createdAt).toLocaleString() : '—'}
        </span>
      )
    },
    {
      header: 'Actions',
      key: 'actions',
      align: 'right',
      render: (r) => (
        <div className="flex items-center justify-end gap-2">
          {r.fileUrl ? (
            <a href={r.fileUrl} target="_blank" rel="noreferrer">
              <Button size="sm" variant="outline" className="border-slate-700 text-xs">
                Download
              </Button>
            </a>
          ) : (
            <span className="text-xs text-slate-500">Processing</span>
          )}
        </div>
      )
    }
  ];

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 text-sm text-slate-400 mb-1">
            <Link to="/reports" className="hover:text-white transition-colors">Reports</Link>
            <span>/</span>
            <span className="text-slate-200">Export History</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
            Report Export History
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Audit trail of generated report files and cloud archived exports.
          </p>
        </div>

        <Link to="/reports">
          <Button variant="outline" size="sm" className="border-slate-700">
            Back to Reports
          </Button>
        </Link>
      </div>

      <DataTable
        columns={columns}
        data={histories}
        isLoading={isLoading}
        emptyMessage="No report export history found."
      />
    </div>
  );
}

export default ReportHistoryPage;
